version: '4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Sapi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: randaro/devopsqaaf:latest
    networks:
      - default
    environment:
      DB_HOST: database
    ports:
      - "8585:8080"
volumes:
  db-volume:
